### ISSUE TITLE
Integrating with ESP-IDF project

### ISSUE THREAD

**Issue by JyotsnaGorle** [craftmetrics/esp32-button#10]
Hi, 

I am trying to use your implementation as a component into my existing ESP-IDF project configuration. I have the following questions.

1. Do I need something more than an ESP32 board and a push button in order to setup the circuit?
2. I am unable to include it as a component.

Do you maybe have a tiny example?

**Comment by chudsaviet** [comment]
I have the component inclusion problem too.
Error:
```
undefined reference to `button_init(unsigned long long)'
```
I'm trying to fix it on my own, but no guarantee.

**Comment by chudsaviet** [comment]
Looks like https://github.com/craftmetrics/esp32-button/pull/11 resolves this.

**Comment by lukecyca** [comment]
Fixed in #11.
