### ISSUE TITLE
Button: NN Long all the time?

### ISSUE THREAD

**Issue by nicklasb** [craftmetrics/esp32-button#21]
Hi,
For some reason, I am getting BUTTON_HELD all the time unless I press the button, at which time i get a BUTTON_DOWN.
But even if I then hold the button, I do not get a new (BUTTON_HELD) event. In fact, I get no event.

The constant BUTTON_HELD I am getting, I am getting even though the actual GPIO is _low_ at the time. 

It is just quite strange, I am probably doing some dumb thing wrong. 
But the combination of GPIO low and BUTTON_HELD is incomprehensible to me..

**Comment by lukecyca** [comment]
By default this library expects that your button signal will be normally high, and pulled low by the button press. This is a very common configuration for microcontrollers.

There is provisions in the code to configure this (look for the `inverted` member variable) but it looks like it is not exposed to the calling code, so it is not convenient to use at the moment.

**Comment by nicklasb** [comment]
Had no idea that was the common way, however it does make sense, of course. 
Feel a little bit dumb, having not realized that until now. :-)

Thanks a lot for your quick reply!!
